### ISSUE TITLE
Loewe FHem in 2020

### ISSUE THREAD

**Issue by jannis6023** [fhem/LoeweTV#4]
Hallo,
ich habe mich bisher noch nicht mit fhem auseinandergesetzt, versuche eigentlich nur mit HomeKit meinen TV Steuern zu können. Da ich bei mir eine HomeBridge laufen habe kam ich auf die Idee, da wiederum dieses FHem-Plugin zu integrieren. Macht das so in 2020 Sinn? Funktioniert das Plugin noch mit dem neuen Chassis / OS?

Würde mich RIESIG freuen, nach dem langen Suchen nach einer Lösung eine gefunden zu haben :)

VG Jannis

**Comment by viegener** [comment]
Hallo Jannis,
leider habe ich selbst inzwischen gar keinen Loewe-Fernseher mehr und kann deshalb eigentlich gar nichts zu Deinen Fragen sagen. Da Loewe inzwischen durch einige Veränderungen gegangen ist, kann es gut sein, dass die neuen Chassis ganz andere Schnittstellen haben.

Generell ist dieses perl-Modul auch nur im Umfeld der Hausautomatisierung FHEM (siehe fhem.de) lauffähig.
